In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy 

# 정상데이터 생성

In [14]:
np.random.seed(seed=100)

In [16]:
mean = [i for i in range(5)]
cov = np.eye(5)

multi_normaldata = np.random.multivariate_normal(mean=mean, cov=cov, size = 500)
print(multi_normaldata)
print(multi_normaldata.shape)

[[-1.25253007  1.17099173  4.77632546  1.77992163  3.65846926]
 [ 0.45476536  1.23842571  1.88339247  2.51946294  3.85855021]
 [ 0.74611436  0.7675508   2.85503085  2.91782044  5.22791719]
 ...
 [ 0.40834327  1.1962631   2.22614264  3.24334059  5.56811999]
 [ 0.04546482  1.54037043  3.33851526  3.94451433  3.52068114]
 [-0.059415    2.12050151  2.06346235  1.66879586  4.61980358]]
(500, 5)


In [17]:
df_normal = pd.DataFrame(multi_normaldata)
df_normal.describe()

0           1           2           3           4
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean    -0.034840    1.056663    2.022291    2.943293    4.058814
std      1.011013    1.043417    0.971748    1.033842    1.029656
min     -2.828131   -1.995659   -0.708962    0.108489    1.116270
25%     -0.716902    0.343868    1.371638    2.181862    3.421487
50%     -0.069669    1.075498    2.083485    2.955267    4.055350
75%      0.632425    1.745825    2.660454    3.671104    4.745957
max      3.447513    3.941900    5.819192    5.676020    7.458597

# 이상데이터 생성