In [232]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.stats import beta

# 데이터 생성

In [233]:
mean = [0 for _ in range(5)]
cov = np.eye(5)
normal = np.random.multivariate_normal(mean=mean, cov=cov, size = 510)

In [234]:
df_normal = pd.DataFrame(normal)
df_normal.describe()

0           1           2           3           4
count  510.000000  510.000000  510.000000  510.000000  510.000000
mean    -0.005997   -0.000352   -0.003165   -0.021829    0.024715
std      0.945806    1.004634    0.958843    0.985300    0.965823
min     -2.801779   -3.457839   -3.143743   -2.427268   -2.593156
25%     -0.653977   -0.700952   -0.635635   -0.652530   -0.647084
50%     -0.014322    0.026938   -0.026835   -0.002857    0.020884
75%      0.664376    0.708343    0.627992    0.598433    0.684639
max      3.506806    3.180742    3.082400    2.583411    3.190569

# 이상데이터 생성

In [235]:
index = np.random.randint(len(normal), size = 10)
print(index)

[ 50 258 312 310 482 378 464 388  27 453]


In [236]:
for idx in index:
    i = np.random.randint(5)
    normal[idx][i] = np.random.uniform(10,20)

In [237]:
for idx in index:
    print(normal[idx])

[-1.61002152 -0.54660351 10.46844344 -0.18305432 -0.54496149]
[ 2.25952269 13.78937796 -0.34473299  0.5448395   0.21925311]
[-0.2553033   0.47768599 -0.64301036  2.4489424  13.30008517]
[-7.15096650e-04 -9.58339570e-01 -1.94531187e+00  1.70116449e+01
  1.66278502e+00]
[ 0.05010485 -0.8685372   0.14011598  0.53968237 11.00233966]
[17.98661905 -1.83646074 -0.05391956  2.13355655 -0.48403602]
[-0.53044561 -1.03000794 -1.1359361   1.13033313 13.73474248]
[-0.8346181  11.88496083  1.54688346 -1.2554936   1.75533976]
[-0.15456394 -0.77742541 -1.09601583 -0.27770575 10.21490064]
[-2.54762621  0.02852739  0.88058677 -0.08166563 10.28517468]


In [238]:
abnormal = pd.DataFrame(normal[index])
print(abnormal)

           0          1          2          3          4
0  -1.610022  -0.546604  10.468443  -0.183054  -0.544961
1   2.259523  13.789378  -0.344733   0.544840   0.219253
2  -0.255303   0.477686  -0.643010   2.448942  13.300085
3  -0.000715  -0.958340  -1.945312  17.011645   1.662785
4   0.050105  -0.868537   0.140116   0.539682  11.002340
5  17.986619  -1.836461  -0.053920   2.133557  -0.484036
6  -0.530446  -1.030008  -1.135936   1.130333  13.734742
7  -0.834618  11.884961   1.546883  -1.255494   1.755340
8  -0.154564  -0.777425  -1.096016  -0.277706  10.214901
9  -2.547626   0.028527   0.880587  -0.081666  10.285175


In [239]:
data = pd.DataFrame(normal)
print(data)
print(data.describe())

            0         1         2         3         4
0    0.000990 -0.473867  0.781396 -0.640097 -0.006279
1   -0.471899  0.135699  0.294581  0.560206  1.905674
2   -0.384861  0.442107 -0.497456  1.070685 -0.128237
3    1.128862  0.163510 -0.083166  1.283647  1.450824
4    0.262030 -0.798552 -0.539829  0.307104  0.897267
..        ...       ...       ...       ...       ...
505  0.248425 -0.338301 -1.099257 -0.260456  0.946239
506  0.283206 -0.563463  1.858679  0.241870 -0.939041
507 -0.432521 -0.582380  1.342277  0.324367 -0.092655
508  0.011062  0.013503  0.426667 -0.305833  1.279180
509  0.771294 -1.660698 -0.021788 -1.850601 -0.975274

[510 rows x 5 columns]
                0           1           2           3           4
count  510.000000  510.000000  510.000000  510.000000  510.000000
mean     0.028551    0.048491    0.017819    0.011282    0.138949
std      1.236567    1.287035    1.065019    1.240844    1.507793
min     -2.801779   -3.457839   -3.143743   -2.427268   -2.59315

In [240]:
array_data = np.array(data)
num_sample = len(data)

p = array_data.shape[1]

col_mean = np.mean(array_data, axis=0)  # column mean
mat_cov = np.cov(array_data.T)  # covariance
mat_inv_s = np.linalg.inv(mat_cov)  # inverse S

values = []
for sample in array_data:
    dif = sample - col_mean
    value = mat_inv_s.dot(dif.T).dot(dif)  # T-square
    values.append(value)

t2 = pd.DataFrame(values, columns=['T2'])

final_data = pd.concat([data,t2], axis=1)

In [241]:
final_data

0         1         2         3         4        T2
0    0.000990 -0.473867  0.781396 -0.640097 -0.006279  0.897790
1   -0.471899  0.135699  0.294581  0.560206  1.905674  1.781831
2   -0.384861  0.442107 -0.497456  1.070685 -0.128237  1.164030
3    1.128862  0.163510 -0.083166  1.283647  1.450824  2.570372
4    0.262030 -0.798552 -0.539829  0.307104  0.897267  0.980163
..        ...       ...       ...       ...       ...       ...
505  0.248425 -0.338301 -1.099257 -0.260456  0.946239  1.613658
506  0.283206 -0.563463  1.858679  0.241870 -0.939041  3.836639
507 -0.432521 -0.582380  1.342277  0.324367 -0.092655  2.087211
508  0.011062  0.013503  0.426667 -0.305833  1.279180  0.806832
509  0.771294 -1.660698 -0.021788 -1.850601 -0.975274  5.007410

[510 rows x 6 columns]

In [242]:
T2 = np.array(values)

for i in range(len(data.columns)):
    
    # d_i 구하기
    final_di = data.drop(data.columns[i], axis=1)
    

    array_data2 = np.array(final_di)
    
    col_mean2 = np.mean(array_data2, axis=0)  # column mean
    mat_cov2 = np.cov(array_data2.T)  # covariance
    mat_inv_s2 = np.linalg.inv(mat_cov2)  # inverse S
    
    values = []
    
    for sample in array_data2:
        dif = sample - col_mean2
        value = mat_inv_s2.dot(dif.T).dot(dif)  # T-square
        values.append(value)
      
    values = np.array(values)
    di = T2 - values
    
    #  globals()['d_{}'.format(i+1)] = di

    
    final_data['d_{}'.format(i+1)] = di  
    
di_table = final_data[['d_1','d_2','d_3','d_4','d_5']]

In [243]:
di_table

d_1       d_2       d_3       d_4       d_5
0    0.001143  0.182133  0.428974  0.214693  0.002764
1    0.137900  0.008344  0.117674  0.173008  1.320219
2    0.110236  0.107282  0.156316  0.691887  0.058962
3    0.835848  0.034602  0.003094  0.961769  0.699818
4    0.028835  0.409080  0.241168  0.014806  0.222830
..        ...       ...       ...       ...       ...
505  0.028672  0.095918  1.138738  0.147153  0.268798
506  0.034480  0.201483  3.018948  0.158747  0.458481
507  0.148347  0.232155  1.606612  0.144347  0.021523
508  0.000053  0.000702  0.143860  0.065966  0.612536
509  0.281328  1.933868  0.056769  2.384168  0.438388

[510 rows x 5 columns]

In [244]:
abnormal_di_table = di_table.loc[index]
print(abnormal_di_table)

            d_1         d_2        d_3         d_4        d_5
50     1.594917    0.176915  96.691173    0.912160   0.038657
258    4.988803  116.418365   0.024597    0.836729   0.040299
312    0.000066    0.277236   0.021145    2.118631  74.367101
310    0.003361    0.013458   0.079606  182.947324   0.040113
482    0.028080    0.358791   0.134535    0.000289  51.757584
378  209.321921    0.648797   0.055305    2.750316   0.028885
464    0.075340    0.504544   0.545680    0.066442  79.863238
388    0.082864   84.043107   2.122796    0.225251   1.620050
27     0.000351    0.344403   0.797104    0.558341  44.481346
453    3.656859    0.000064   0.968537    0.121226  45.188970


In [245]:
cutoff = scipy.stats.chi2.ppf(1-.01, df=1)
cutoff

6.6348966010212145

In [246]:
threshold = abnormal_di_table > cutoff
threshold.sum().sort_values(ascending=False)

d_5    5
d_2    2
d_1    1
d_3    1
d_4    1
dtype: int64

In [247]:
average = abnormal_di_table.mean()
average.sort_values(ascending=False)

d_5    29.742624
d_1    21.975256
d_2    20.278568
d_4    19.053671
d_3    10.144048
dtype: float64

In [248]:
rank_sum_table = abnormal_di_table
print(rank_sum_table)

            d_1         d_2        d_3         d_4        d_5
50     1.594917    0.176915  96.691173    0.912160   0.038657
258    4.988803  116.418365   0.024597    0.836729   0.040299
312    0.000066    0.277236   0.021145    2.118631  74.367101
310    0.003361    0.013458   0.079606  182.947324   0.040113
482    0.028080    0.358791   0.134535    0.000289  51.757584
378  209.321921    0.648797   0.055305    2.750316   0.028885
464    0.075340    0.504544   0.545680    0.066442  79.863238
388    0.082864   84.043107   2.122796    0.225251   1.620050
27     0.000351    0.344403   0.797104    0.558341  44.481346
453    3.656859    0.000064   0.968537    0.121226  45.188970


In [249]:
rank_sum = [1,2,3,4,5]


for i in range(len(rank_sum_table)):

    rank = rank_sum_table.iloc[i]
    rank_sort = rank_sum_table.iloc[i].sort_values()  
    
    for j in range(len(rank)):
        rank_sort[j] = rank_sum[j]
        
        for index in rank.index:
            rank[index] = rank_sort[index]
            
    rank_sum_table.loc[i] = rank   

In [250]:
rank_sum_table

d_1  d_2  d_3  d_4  d_5
50   4.0  2.0  5.0  3.0  1.0
258  4.0  5.0  1.0  3.0  2.0
312  1.0  3.0  2.0  4.0  5.0
310  1.0  2.0  4.0  5.0  3.0
482  2.0  4.0  3.0  1.0  5.0
378  5.0  3.0  2.0  4.0  1.0
464  2.0  3.0  4.0  1.0  5.0
388  1.0  5.0  4.0  2.0  3.0
27   1.0  2.0  4.0  3.0  5.0
453  4.0  1.0  3.0  2.0  5.0
0    4.0  2.0  5.0  3.0  1.0
1    4.0  5.0  1.0  3.0  2.0
2    1.0  3.0  2.0  4.0  5.0
3    1.0  2.0  4.0  5.0  3.0
4    2.0  4.0  3.0  1.0  5.0
5    5.0  3.0  2.0  4.0  1.0
6    2.0  3.0  4.0  1.0  5.0
7    1.0  5.0  4.0  2.0  3.0
8    1.0  2.0  4.0  3.0  5.0
9    4.0  1.0  3.0  2.0  5.0

In [251]:
rank_sum_table.sum()

d_1    50.0
d_2    60.0
d_3    64.0
d_4    56.0
d_5    70.0
dtype: float64

In [252]:
rank_sum_table.sum().sort_values(ascending=False)

d_5    70.0
d_3    64.0
d_2    60.0
d_4    56.0
d_1    50.0
dtype: float64

In [253]:
a = rank_sum_table.sum().sum()
print(a)

300.0


In [254]:
b = rank_sum_table.sum() / a
print(b.sort_values(ascending=False))

d_5    0.233333
d_3    0.213333
d_2    0.200000
d_4    0.186667
d_1    0.166667
dtype: float64
